"""empty message

Revision ID: 283230e6e1ff
Revises: cf249eb43042
Create Date: 2023-10-03 17:58:21.532414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283230e6e1ff'
down_revision = 'cf249eb43042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('done_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('cancel_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('cancel_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('done_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
