"""empty message

Revision ID: 518c01308f50
Revises: 5e7a66839815
Create Date: 2023-10-02 20:58:01.763209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518c01308f50'
down_revision = '5e7a66839815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
