"""empty message

Revision ID: 5e7a66839815
Revises: e83c8bf7a4b5
Create Date: 2023-09-27 16:59:12.196228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7a66839815'
down_revision = 'e83c8bf7a4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=300), nullable=True))

    # ### end Alembic commands ###
