"""empty message

Revision ID: 628e87b74672
Revises: 2217e6132010
Create Date: 2023-10-05 16:31:56.464202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628e87b74672'
down_revision = '2217e6132010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('ingredient')

    # ### end Alembic commands ###
