"""empty message

Revision ID: 6b2ad88d0aa8
Revises: 
Create Date: 2023-09-27 15:52:04.408988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2ad88d0aa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ordertable')
    op.drop_table('remains')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remains',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('blacktea', sa.INTEGER(), nullable=False),
    sa.Column('cocoa', sa.INTEGER(), nullable=False),
    sa.Column('coffee', sa.INTEGER(), nullable=False),
    sa.Column('greentea', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordertable',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=10), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order')
    op.drop_table('menu')
    op.drop_table('cart')
    # ### end Alembic commands ###
