"""empty message

Revision ID: 71204677696d
Revises: 61dc7b91c939
Create Date: 2023-10-02 21:50:41.776837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71204677696d'
down_revision = '61dc7b91c939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
