"""empty message

Revision ID: 978b0e26bbae
Revises: bb99be888651
Create Date: 2023-10-03 19:47:39.491915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978b0e26bbae'
down_revision = 'bb99be888651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('menu')

    # ### end Alembic commands ###
