"""empty message

Revision ID: e71eb417fe41
Revises: aa31c8c0c593
Create Date: 2023-10-02 21:07:46.988380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71eb417fe41'
down_revision = 'aa31c8c0c593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=False))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('done_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('cancel_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('cancel_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('done_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
